#!/bin/sh

## kind of any ugly hack
read checkout repo upstream<<EOF
`grep '^'$1 ./forks`
EOF

## clone the repository
rm -rf $checkout
git clone $repo

## ...we came in
cd $checkout

## configure the upstream remote
git remote add upstream $upstream

## everybody remember where we parked
origbranch=`git branch | fgrep '*' | awk '{print $2}'`

## set up all of the remote-tracking branches
for branch in `git branch -r | grep -v '\(^  upstream/\|^  origin/HEAD\)' | sed -e 's/  origin\///' | fgrep -v $origbranch`; do
    git checkout -b $branch --track origin/$branch
done

## isn't this where...
git checkout $origbranch
cd ..

## leave updating the remote-tracking branches for another script
#./update-fork $checkout
