#!/bin/sh

checkout="`basename $1`"
repo="git@github.com:$1"
upstream="git@github.com:$2/$checkout"

## clone the repository
git clone $repo

## ...we came in
cd $checkout

## configure the upstream remote
git remote add upstream $upstream
git fetch upstream

## everybody remember where we parked
origbranch=`git branch | fgrep '*' | awk '{print $2}'`

## set up all of the remote-tracking branches
for branch in `git branch -r | grep '^  upstream' | sed -e 's/  upstream\///'`; do
    if [ "$branch" != "$origbranch" ]; then
	git checkout -b $branch --track origin/$branch
    else
	## the default branch (usually `master` or `develop`) is
	## already set up to track its origin
	git checkout $branch
    fi
    git merge --ff-only upstream/$branch
    git push
done

## isn't this where...
git checkout $origbranch
cd ..

## add this repo to the list of checked out forks
echo $checkout $repo $upstream >> forks
