#!/bin/sh

fork=$1

## make sure the fork exists
if [ ! -d $fork ]; then
    ./setup-fork-again $fork
fi

## ...we came in?
cd $fork

## sync with the upstream repo
branches=$(git fetch upstream 2>&1 | tee /dev/fd/2 | fgrep .. | awk '{print $2}')

## everybody remember where we parked
origbranch=`git branch | fgrep '*' | awk '{print $2}'`

## sync the branches updated upstream
for branch in $branches; do
    git checkout $branch
    git merge --ff-only upstream/$branch
    git push
done

## isn't this where...
git checkout $origbranch
cd ..
